version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  python-server:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - mongodb
    environment:
      MYSQL_HOST: mysql
      MONGO_HOST: mongodb

volumes:
  mysql_data:
  mongo_data:
